import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../public/css/dark.css";
import { ThemeProvider } from "next-themes";
import Header from "./components/Header";
import { Poppins } from "next/font/google";
import ScrollToTopButton from "./components/CursorToTop";
import MouseCursor from "./components/MouseCursor";
import MobileFooter from "./components/MobileFooter"; 

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ectorious ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} ${poppins.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <ScrollToTopButton />
          <MouseCursor />
          {children}
          <MobileFooter /> 
        </ThemeProvider>
      </body>
    </html>
  );
}
